version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      all-dependencies:
        patterns:
          - "*"
    reviewers:
      - merlinf14b
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    labels:
      - ci
