minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@rolldown/*" # sub-dependencies of vite@8.x
  - "@napi-rs/*" # sub-dependencies of vite@8.x
  - "@tanstack/router-core" # sub-dependency of @tanstack/react-router
